# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-08 09:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='duankou_rongqi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rongqi_duankou', models.IntegerField(help_text='\u586b\u5199\u9700\u8981\u5f00\u653e\u7684\u5916\u90e8\u7aef\u53e3')),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='guanli_rongqi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rongqi_ip', models.GenericIPAddressField(help_text='\u586b\u5199\u5bb9\u5668\u7684\u5916\u90e8ip\u5730\u5740')),
                ('rongqi_id', models.CharField(max_length=100)),
                ('rongqi_create_mingzi', models.CharField(max_length=100)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='shenqing_rongqi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shenqing_mingzi', models.CharField(help_text='\u7533\u8bf7\u5bb9\u5668\u7684\u540d\u79f0\uff0c\u4e0d\u80fd\u548c\u5176\u4ed6\u4eba\u91cd\u590d', max_length=100, unique=True)),
                ('shenqing_status', models.CharField(choices=[('1', '\u7533\u8bf7\u63d0\u4ea4'), ('2', '\u7533\u8bf7\u6210\u529f'), ('3', '\u7533\u8bf7\u5931\u8d25')], default='1', max_length=1)),
                ('use_flag', models.IntegerField(default=1)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='type_rongqi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rongqi_type', models.CharField(max_length=100)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='shenqing_rongqi',
            name='type_rongqi_id',
            field=models.ForeignKey(help_text='\u9009\u62e9\u4e00\u4e2a\u7236\u5bb9\u5668', on_delete=django.db.models.deletion.CASCADE, to='rongqi.type_rongqi'),
        ),
        migrations.AddField(
            model_name='shenqing_rongqi',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guanli_rongqi',
            name='shenqing_rongqi_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rongqi.shenqing_rongqi'),
        ),
        migrations.AddField(
            model_name='duankou_rongqi',
            name='shenqing_rongqi_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rongqi.shenqing_rongqi'),
        ),
    ]
