# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-08 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rongqi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='type_rongqi',
            name='rongqi_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
