# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-08 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rongqi', '0002_type_rongqi_rongqi_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duankou_rongqi',
            name='rongqi_duankou',
            field=models.IntegerField(default=22),
        ),
        migrations.AlterField(
            model_name='shenqing_rongqi',
            name='shenqing_status',
            field=models.CharField(choices=[(b'1', b'\xe7\x94\xb3\xe8\xaf\xb7\xe6\x8f\x90\xe4\xba\xa4'), (b'2', b'\xe7\x94\xb3\xe8\xaf\xb7\xe6\x88\x90\xe5\x8a\x9f'), (b'3', b'\xe7\x94\xb3\xe8\xaf\xb7\xe5\xa4\xb1\xe8\xb4\xa5')], default=b'1', max_length=1),
        ),
    ]
