# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-08 15:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rongqi', '0003_auto_20161108_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='ipaddress_rongqi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_name', models.CharField(choices=[(b'1', b'PHP\xe7\xa0\x94\xe5\x8f\x91\xe9\x83\xa8\xe9\x97\xa8'), (b'2', b'QA\xe9\x83\xa8\xe9\x97\xa8'), (b'3', b'\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93\xe9\x83\xa8\xe9\x97\xa8'), (b'4', b'JAVA\xe9\x83\xa8\xe9\x97\xa8')], help_text='ip\u90e8\u95e8\u540d\u79f0,1->php\u7814\u53d1\u90e8 2->\u6d4b\u8bd5 3->DB,4->java', max_length=50)),
                ('ip', models.GenericIPAddressField()),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u7684\u65f6\u95f4')),
            ],
        ),
        migrations.AlterModelOptions(
            name='duankou_rongqi',
            options={'verbose_name': '\u7ed1\u5b9a\u5bb9\u5668\u5916\u90e8\u7aef\u53e3', 'verbose_name_plural': '\u7ed1\u5b9a\u5bb9\u5668\u5916\u90e8\u7aef\u53e3'},
        ),
        migrations.AlterModelOptions(
            name='guanli_rongqi',
            options={'verbose_name': '\u7ba1\u7406\u5bb9\u5668', 'verbose_name_plural': '\u7ba1\u7406\u5bb9\u5668'},
        ),
        migrations.AlterModelOptions(
            name='shenqing_rongqi',
            options={'verbose_name': '\u7533\u8bf7\u5bb9\u5668', 'verbose_name_plural': '\u7533\u8bf7\u5bb9\u5668'},
        ),
        migrations.AlterModelOptions(
            name='type_rongqi',
            options={'verbose_name': '\u4e3b\u5bb9\u5668\u7c7b\u578b', 'verbose_name_plural': '\u4e3b\u5bb9\u5668\u7c7b\u578b'},
        ),
        migrations.AlterField(
            model_name='duankou_rongqi',
            name='create_date',
            field=models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u7684\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='duankou_rongqi',
            name='rongqi_duankou',
            field=models.IntegerField(verbose_name='\u5bb9\u5668\u5916\u90e8\u7aef\u53e3'),
        ),
        migrations.AlterField(
            model_name='duankou_rongqi',
            name='shenqing_rongqi_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rongqi.shenqing_rongqi', verbose_name='\u7533\u8bf7\u5bb9\u5668\u7684ID'),
        ),
        migrations.AlterField(
            model_name='guanli_rongqi',
            name='create_date',
            field=models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u7684\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='guanli_rongqi',
            name='rongqi_create_mingzi',
            field=models.CharField(max_length=100, unique=True, verbose_name='\u751f\u6210\u5bb9\u5668\u7684\u522b\u540d'),
        ),
        migrations.AlterField(
            model_name='guanli_rongqi',
            name='rongqi_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='\u751f\u6210\u5bb9\u5668ID'),
        ),
        migrations.AlterField(
            model_name='guanli_rongqi',
            name='rongqi_ip',
            field=models.ForeignKey(help_text='\u586b\u5199\u5bb9\u5668\u7684\u5916\u90e8ip\u5730\u5740', on_delete=django.db.models.deletion.CASCADE, to='rongqi.ipaddress_rongqi', unique=True, verbose_name='\u5bb9\u5668\u7ed1\u5b9a\u7684IP'),
        ),
        migrations.AlterField(
            model_name='guanli_rongqi',
            name='shenqing_rongqi_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rongqi.shenqing_rongqi', verbose_name='\u7533\u8bf7\u5bb9\u5668\u7684ID'),
        ),
        migrations.AlterField(
            model_name='shenqing_rongqi',
            name='create_date',
            field=models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u7684\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='shenqing_rongqi',
            name='shenqing_mingzi',
            field=models.CharField(help_text='\u7533\u8bf7\u5bb9\u5668\u7684\u540d\u79f0\uff0c\u4e0d\u80fd\u548c\u5176\u4ed6\u4eba\u91cd\u590d', max_length=100, unique=True, verbose_name='\u7533\u8bf7\u5bb9\u5668\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='shenqing_rongqi',
            name='shenqing_status',
            field=models.CharField(choices=[(b'1', b'\xe7\x94\xb3\xe8\xaf\xb7\xe6\x8f\x90\xe4\xba\xa4'), (b'2', b'\xe7\x94\xb3\xe8\xaf\xb7\xe6\x88\x90\xe5\x8a\x9f'), (b'3', b'\xe7\x94\xb3\xe8\xaf\xb7\xe5\xa4\xb1\xe8\xb4\xa5')], default=b'1', max_length=1, verbose_name='\u7533\u8bf7\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='shenqing_rongqi',
            name='type_rongqi_id',
            field=models.ForeignKey(help_text='\u9009\u62e9\u4e00\u4e2a\u7236\u5bb9\u5668', on_delete=django.db.models.deletion.CASCADE, to='rongqi.type_rongqi', verbose_name='\u7236\u5bb9\u5668'),
        ),
        migrations.AlterField(
            model_name='shenqing_rongqi',
            name='use_flag',
            field=models.IntegerField(default=1, verbose_name='\u903b\u8f91\u5220\u9664\u6807\u8bc6'),
        ),
        migrations.AlterField(
            model_name='shenqing_rongqi',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237id'),
        ),
        migrations.AlterField(
            model_name='type_rongqi',
            name='create_date',
            field=models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u7684\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='type_rongqi',
            name='rongqi_name',
            field=models.CharField(max_length=100, verbose_name='\u5bb9\u5668\u522b\u540d'),
        ),
        migrations.AlterField(
            model_name='type_rongqi',
            name='rongqi_type',
            field=models.CharField(max_length=100, verbose_name='\u4e3b\u5bb9\u5668\u7c7b\u578b'),
        ),
    ]
