# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-08 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rongqi', '0004_auto_20161108_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddress_rongqi',
            options={'verbose_name': '\u6dfb\u52a0\u5bb9\u5668IP', 'verbose_name_plural': '\u6dfb\u52a0\u5bb9\u5668IP'},
        ),
        migrations.AddField(
            model_name='ipaddress_rongqi',
            name='is_enable',
            field=models.BooleanField(default=False, help_text='\u9ed8\u8ba4\u4e3a\u5b9e\u7528'),
        ),
    ]
