# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rongqi', '0005_auto_20161108_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress_rongqi',
            name='ip',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name='ipaddress_rongqi',
            name='is_enable',
            field=models.BooleanField(default=False, help_text='\u9ed8\u8ba4\u5173\u95ed'),
        ),
        migrations.AlterField(
            model_name='shenqing_rongqi',
            name='shenqing_status',
            field=models.CharField(choices=[(b'1', b'\xe7\x94\xb3\xe8\xaf\xb7\xe6\x8f\x90\xe4\xba\xa4'), (b'2', b'\xe7\x94\xb3\xe8\xaf\xb7\xe6\x88\x90\xe5\x8a\x9f'), (b'3', b'\xe7\x94\xb3\xe8\xaf\xb7\xe5\xa4\xb1\xe8\xb4\xa5'), (b'4', b'\xe6\x9c\xaa\xe7\x94\xb3\xe8\xaf\xb7')], default=b'4', max_length=1, verbose_name='\u7533\u8bf7\u72b6\u6001'),
        ),
    ]
