# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-10 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rongqi', '0009_auto_20161110_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guanli_rongqi',
            name='rongqi_create_mingzi',
        ),
    ]
