# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-11 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rongqi', '0010_remove_guanli_rongqi_rongqi_create_mingzi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shenqing_rongqi',
            name='shenqing_mingzi',
            field=models.CharField(help_text='\u7533\u8bf7\u5bb9\u5668\u7684\u540d\u79f0', max_length=100, verbose_name='\u7533\u8bf7\u5bb9\u5668\u540d\u79f0'),
        ),
    ]
