# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-15 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rongqi', '0012_shenqing_rongqi_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shenqing_rongqi',
            name='end_date',
            field=models.DateTimeField(help_text='\u6b64\u9009\u9879\u5fc5\u586b', verbose_name='\u5bb9\u5668\u4f7f\u7528\u7ed3\u675f\u65f6\u95f4'),
        ),
    ]
