# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rongqi', '0015_auto_20161116_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='guanli_rongqi',
            name='external_directory',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pipaddress_rongqi',
            name='geteway',
            field=models.GenericIPAddressField(default='192.168.0.3', verbose_name='\u7f51\u5173'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ipaddress_rongqi',
            name='ip_name',
            field=models.CharField(choices=[(b'1', b'\xe7\xa0\x94\xe5\x8f\x91\xe9\x83\xa8\xe9\x97\xa8'), (b'2', b'\xe6\x9e\xb6\xe6\x9e\x84\xe9\x83\xa8\xe9\x97\xa8'), (b'3', b'\xe6\xb5\x8b\xe8\xaf\x95\xe9\x83\xa8\xe9\x97\xa8')], help_text='\u90e8\u95e8\u540d\u79f0,1->\u7814\u53d1\u90e8\u95e8 2->\u67b6\u6784\u90e8\u95e8 3->\u6d4b\u8bd5\u90e8\u95e8', max_length=50),
        ),
    ]
