# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-21 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='didian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='\u5730\u65b9\u522b\u540d', max_length=60, verbose_name='\u5730\u65b9\u522b\u540d')),
                ('name', models.CharField(help_text='\u5730\u65b9', max_length=60, verbose_name='\u5730\u65b9')),
            ],
            options={
                'verbose_name': '\u5730\u65b9',
                'verbose_name_plural': '\u5730\u65b9',
            },
        ),
        migrations.CreateModel(
            name='fu_lujing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='\u7236\u8def\u5f84\u522b\u540d', max_length=60, verbose_name='\u7236\u8def\u5f84\u522b\u540d')),
                ('name', models.CharField(help_text='\u7236\u8def\u5f84', max_length=255, verbose_name='\u7236\u8def\u5f84')),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u7236\u8def\u5f84',
                'verbose_name_plural': '\u7236\u8def\u5f84',
            },
        ),
        migrations.CreateModel(
            name='jilu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(help_text='\u7ebf\u4e0a\u4e3b\u673a\u540d', max_length=60, verbose_name='\u7ebf\u4e0a\u4e3b\u673a\u540d')),
                ('neirong', models.CharField(max_length=255, verbose_name='\u8def\u5f84\u4fe1\u606f')),
                ('didian_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyinotifys.didian', verbose_name='\u5730\u70b9')),
            ],
            options={
                'verbose_name': '\u8bb0\u5f55',
                'verbose_name_plural': '\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='zhuangtai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='\u72b6\u6001\u522b\u540d', max_length=60, verbose_name='\u72b6\u6001\u522b\u540d')),
                ('name', models.CharField(help_text='\u72b6\u6001\u6307\u589e\u5220\u6539\u67e5\u7b49...', max_length=120)),
            ],
            options={
                'verbose_name': '\u72b6\u6001',
                'verbose_name_plural': '\u72b6\u6001',
            },
        ),
        migrations.CreateModel(
            name='zi_lujing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='\u5b50\u8def\u5f84\u522b\u540d', max_length=60, verbose_name='\u5b50\u8def\u5f84\u522b\u540d')),
                ('name', models.CharField(help_text='\u5b50\u8def\u5f84\u7684\u76ee\u7684\u5bf9\u5e94\u6392\u9664', max_length=255, verbose_name='\u7236\u8def\u5f84')),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u5b50\u8def\u5f84',
                'verbose_name_plural': '\u5b50\u8def\u5f84',
            },
        ),
        migrations.AddField(
            model_name='jilu',
            name='zhuangtai_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyinotifys.zhuangtai', verbose_name='\u72b6\u6001'),
        ),
    ]
