# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-18 13:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='leixing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u5de5\u5355\u7684\u7c7b\u578b', max_length=255, verbose_name='\u5de5\u5355\u7c7b\u578b')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='shijian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fujian', models.FileField(blank=True, upload_to='./update/', verbose_name='\u9644\u4ef6')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('create_end', models.DateTimeField(blank=True, help_text='\u9009\u586b', verbose_name='\u5de5\u5355\u6709\u6548\u671f')),
                ('beizhu', models.TextField(blank=True, verbose_name='\u5907\u6ce8')),
                ('leixing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gongdan.leixing', verbose_name='\u5de5\u5355\u7c7b\u578b')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237id')),
            ],
        ),
    ]
