# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-18 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gongdan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shijian',
            name='create_end',
            field=models.CharField(blank=True, help_text='\u9009\u586b', max_length=30, verbose_name='\u5de5\u5355\u6709\u6548\u671f'),
        ),
    ]
