# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-18 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gongdan', '0002_auto_20170118_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shijian',
            name='create_end',
        ),
    ]
