# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-18 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gongdan', '0004_shijian_create_end'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leixing',
            options={'verbose_name': '\u5de5\u5355\u7c7b\u578b', 'verbose_name_plural': '\u5de5\u5355\u7c7b\u578b'},
        ),
        migrations.AlterModelOptions(
            name='shijian',
            options={'verbose_name': '\u5de5\u5355\u7533\u8bf7', 'verbose_name_plural': '\u5de5\u5355\u7533\u8bf7'},
        ),
        migrations.AddField(
            model_name='shijian',
            name='is_shenqing',
            field=models.BooleanField(default=False, verbose_name='\u7533\u8bf7\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='shijian',
            name='create_end',
            field=models.DateField(blank=True),
        ),
    ]
