# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-18 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gongdan', '0005_auto_20170118_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='shijian',
            name='is_chuli',
            field=models.BooleanField(default=False, verbose_name='\u5904\u7406\u72b6\u6001'),
        ),
    ]
