# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-18 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gongdan', '0006_shijian_is_chuli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shijian',
            name='create_end',
            field=models.DateField(blank=True, help_text='\u6839\u636e\u60c5\u51b5,\u9009\u586b', verbose_name='\u7ed3\u675f\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='shijian',
            name='is_shenqing',
            field=models.CharField(choices=[('0', '\u672a\u7533\u8bf7'), ('1', '\u7533\u8bf7\u63d0\u4ea4'), ('2', '\u5df2\u5904\u7406')], max_length=50, verbose_name='\u7533\u8bf7\u72b6\u6001'),
        ),
    ]
