# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-19 08:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gongdan', '0007_auto_20170118_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shijian',
            name='is_shenqing',
            field=models.CharField(choices=[('0', '\u672a\u7533\u8bf7'), ('1', '\u7533\u8bf7\u63d0\u4ea4'), ('2', '\u5df2\u5904\u7406')], default='0', max_length=50, verbose_name='\u7533\u8bf7\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='shijian',
            name='user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237id'),
        ),
    ]
