# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-19 09:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gongdan', '0008_auto_20170119_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shijian',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237id'),
        ),
    ]
