# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-28 09:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='logsdownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u9879\u76ee')),
                ('log_dir', models.CharField(max_length=255, verbose_name='\u65e5\u5fd7\u5b58\u653e\u8def\u5f84')),
                ('war_file', models.CharField(max_length=255, verbose_name='war\u5305\u6587\u4ef6')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u65e5\u5fd7\u4e0b\u8f7d',
                'verbose_name_plural': '\u65e5\u5fd7\u4e0b\u8f7d',
            },
        ),
    ]
