# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-19 10:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='didian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u90a3\u4e2a\u5730\u65b9\u51fa\u7684\u95ee\u9898', max_length=100, verbose_name='\u5730\u70b9')),
            ],
            options={
                'verbose_name': '\u5730\u70b9',
                'verbose_name_plural': '\u5730\u70b9',
            },
        ),
        migrations.CreateModel(
            name='guzhang_biaoxian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u6545\u969c\u8868\u73b0', max_length=255, verbose_name='\u6545\u969c\u8868\u73b0')),
            ],
            options={
                'verbose_name': '\u6545\u969c\u8868\u73b0',
                'verbose_name_plural': '\u6545\u969c\u8868\u73b0',
            },
        ),
        migrations.CreateModel(
            name='guzhang_jilu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shijian_riqi', models.DateField(help_text='\u4e8b\u4ef6\u65e5\u671f', verbose_name='\u4e8b\u4ef6\u65e5\u671f')),
                ('fasheng_shijian', models.TimeField(verbose_name='\u53d1\u751f\u65f6\u95f4')),
                ('shouli_shijian', models.DateTimeField(verbose_name='\u4e8b\u4ef6\u53d7\u7406\u65f6\u95f4')),
                ('huifu_shijian', models.DateTimeField(verbose_name='\u6062\u590d\u65f6\u95f4')),
                ('sj_chili', models.CharField(max_length=255, verbose_name='\u5904\u7406\u529e\u6cd5')),
                ('note', models.TextField(verbose_name='\u5907\u6ce8')),
                ('gz_biaoxian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faillog.guzhang_biaoxian', verbose_name='\u6545\u969c\u8868\u73b0')),
                ('host_didian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faillog.didian', verbose_name='\u670d\u52a1\u5668\u5730\u70b9')),
            ],
            options={
                'verbose_name': '\u6545\u969c\u8bb0\u5f55',
                'verbose_name_plural': '\u6545\u969c\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='shijian_chuliren',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(help_text='\u4e8b\u4ef6\u5904\u7406\u4eba', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4e8b\u4ef6\u5904\u7406\u4eba')),
            ],
            options={
                'verbose_name': '\u4e8b\u4ef6\u5904\u7406\u4eba',
                'verbose_name_plural': '\u4e8b\u4ef6\u5904\u7406\u4eba',
            },
        ),
        migrations.CreateModel(
            name='shijian_jibie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('p0', '\u9ad8'), ('p1', '\u4e2d'), ('p2', '\u4f4e')], help_text='\n      \u4e8b\u4ef6\u7ea7\u522b\u89e3\u91ca\uff1a\nP0\uff1a\u7ebf\u4e0a\u4e1a\u52a1\u76f8\u5173\uff08\u4e3b\u8981\u662f\u6307\u5f71\u54cd\u4ea4\u6613\u7684\u4e8b\u6545\uff0c\u6bd4\u5982\u4e3b\u7ad9\u3001m\u7ad9\u3001help\u65e0\u6cd5\u8bbf\u95ee\u3001\u767b\u5f55\u3001\u52a0\u5165\u8d2d\u7269\u8f66\u7b49\u5f71\u54cd\u8303\u56f4\u5927\uff0c\u7a0b\u5ea6\u9ad8\u7684\u4e8b\u4ef6\uff09\nP1\uff1a\u8bdd\u52a1\u7cfb\u7edf\u3001\u90ae\u7bb1\u3001\u5de5\u4f5c\u7ad9\u3001erp\u3001crm\u3001IM\u3001\u5185\u7f51\u7f51\u7edc \u7b49\u5f71\u54cd\u8303\u56f4\u5e7f\uff0c\u7a0b\u5ea6\u4e2d\u7684\u4e8b\u4ef6\nP2\uff1a\u8003\u8bd5\u7cfb\u7edf\u3001\u91d1\u8776\u3001\u8003\u52e4\u7b49\u7a0b\u5ea6\u4f4e\u7684\u4e00\u822c\u4e8b\u4ef6\n\n      ', max_length=60, verbose_name='\u4e8b\u4ef6\u7ea7\u522b')),
            ],
            options={
                'verbose_name': '\u4e8b\u4ef6\u7ea7\u522b',
                'verbose_name_plural': '\u4e8b\u4ef6\u7ea7\u522b',
            },
        ),
        migrations.CreateModel(
            name='shijian_shouliren',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(help_text='\u4e8b\u4ef6\u53d7\u7406\u4eba', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4e8b\u4ef6\u53d7\u7406\u4eba')),
            ],
            options={
                'verbose_name': '\u4e8b\u4ef6\u53d7\u7406\u4eba',
                'verbose_name_plural': '\u4e8b\u4ef6\u53d7\u7406\u4eba',
            },
        ),
        migrations.CreateModel(
            name='shijian_tichuzhe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(help_text='\u4e8b\u4ef6\u63d0\u51fa\u8005,\u76d1\u63a7\u4eba', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4e8b\u4ef6\u63d0\u51fa\u8005')),
            ],
            options={
                'verbose_name': '\u4e8b\u4ef6\u63d0\u51fa\u8005',
                'verbose_name_plural': '\u4e8b\u4ef6\u63d0\u51fa\u8005',
            },
        ),
        migrations.CreateModel(
            name='shijian_yuanyin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u4e8b\u4ef6\u539f\u56e0', max_length=255, verbose_name='\u4e8b\u4ef6\u539f\u56e0')),
            ],
            options={
                'verbose_name': '\u4e8b\u4ef6\u539f\u56e0',
                'verbose_name_plural': '\u4e8b\u4ef6\u539f\u56e0',
            },
        ),
        migrations.CreateModel(
            name='yingyong_host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u5e94\u7528\u670d\u52a1\u5668', max_length=100, verbose_name='\u5e94\u7528\u670d\u52a1\u5668')),
            ],
            options={
                'verbose_name': '\u5e94\u7528\u670d\u52a1\u5668',
                'verbose_name_plural': '\u5e94\u7528\u670d\u52a1\u5668',
            },
        ),
        migrations.AddField(
            model_name='guzhang_jilu',
            name='sj_chuliren',
            field=models.ManyToManyField(to='faillog.shijian_chuliren', verbose_name='\u4e8b\u4ef6\u5904\u7406\u4eba'),
        ),
        migrations.AddField(
            model_name='guzhang_jilu',
            name='sj_jibie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faillog.shijian_jibie', verbose_name='\u4e8b\u4ef6\u7ea7\u522b'),
        ),
        migrations.AddField(
            model_name='guzhang_jilu',
            name='sj_shouliren',
            field=models.ManyToManyField(to='faillog.shijian_shouliren', verbose_name='\u4e8b\u4ef6\u53d7\u7406\u4eba'),
        ),
        migrations.AddField(
            model_name='guzhang_jilu',
            name='sj_tichuzhe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faillog.shijian_tichuzhe', verbose_name='\u4e8b\u4ef6\u63d0\u51fa\u8005'),
        ),
        migrations.AddField(
            model_name='guzhang_jilu',
            name='sj_yuanyin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faillog.shijian_yuanyin', verbose_name='\u4e8b\u4ef6\u539f\u56e0'),
        ),
        migrations.AddField(
            model_name='guzhang_jilu',
            name='yy_host',
            field=models.ManyToManyField(to='faillog.yingyong_host', verbose_name='\u5e94\u7528\u670d\u52a1\u5668'),
        ),
    ]
