# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-25 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faillog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guzhang_jilu',
            name='note',
            field=models.TextField(blank=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='guzhang_jilu',
            name='sj_jibie',
            field=models.ForeignKey(help_text='\n\n      \u4e8b\u4ef6\u7ea7\u522b\u89e3\u91ca\uff1a\nP0\uff1a\u7ebf\u4e0a\u4e1a\u52a1\u76f8\u5173\uff08\u4e3b\u8981\u662f\u6307\u5f71\u54cd\u4ea4\u6613\u7684\u4e8b\u6545\uff0c\u6bd4\u5982\u4e3b\u7ad9\u3001m\u7ad9\u3001help\u65e0\u6cd5\u8bbf\u95ee\u3001\u767b\u5f55\u3001\u52a0\u5165\u8d2d\u7269\u8f66\u7b49\u5f71\u54cd\u8303\u56f4\u5927\uff0c\u7a0b\u5ea6\u9ad8\u7684\u4e8b\u4ef6\uff09\nP1\uff1a\u8bdd\u52a1\u7cfb\u7edf\u3001\u90ae\u7bb1\u3001\u5de5\u4f5c\u7ad9\u3001erp\u3001crm\u3001IM\u3001\u5185\u7f51\u7f51\u7edc \u7b49\u5f71\u54cd\u8303\u56f4\u5e7f\uff0c\u7a0b\u5ea6\u4e2d\u7684\u4e8b\u4ef6\nP2\uff1a\u8003\u8bd5\u7cfb\u7edf\u3001\u91d1\u8776\u3001\u8003\u52e4\u7b49\u7a0b\u5ea6\u4f4e\u7684\u4e00\u822c\u4e8b\u4ef6\n\n                                 ', on_delete=django.db.models.deletion.CASCADE, to='faillog.shijian_jibie', verbose_name='\u4e8b\u4ef6\u7ea7\u522b'),
        ),
    ]
