# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-17 10:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='extend_user_permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.CharField(choices=[('1', '\u53d1\u7248\u7528\u6237'), ('2', '\u53d1\u7248\u5ba1\u6838\u7528\u6237')], help_text='\u6807\u8bc6\u7528\u6237\u7684\u53d1\u7248\u6743\u9650', max_length=10, verbose_name='\u7528\u6237\u6743\u9650')),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u6269\u5c55\u7528\u6237\u6743\u9650',
                'verbose_name_plural': '\u6269\u5c55\u7528\u6237\u6743\u9650',
            },
        ),
        migrations.CreateModel(
            name='faban_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u53d1\u7248\u5e94\u7528', max_length=30, verbose_name='\u53d1\u7248\u5e94\u7528')),
                ('wu_id', models.CharField(blank=True, default='0', help_text='\u7279\u6b8a\u5b57\u6bb5,\u53ea\u7528\u4e8e\u6ca1\u6709\u6743\u9650\u7684\u7528\u6237,\u53ea\u80fd\u6709\u4e00\u4e2a\u5b57\u6bb5\u548c\u5b83\u5339\u914d', max_length=1)),
                ('jiaoben', models.CharField(help_text='\u5e94\u7528\u5bf9\u5e94\u7684\u811a\u672c', max_length=100, verbose_name='\u53d1\u7248\u811a\u672c')),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u53d1\u7248\u5e94\u7528',
                'verbose_name_plural': '\u53d1\u7248\u5e94\u7528',
            },
        ),
        migrations.CreateModel(
            name='faban_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upfile', models.FileField(help_text='\u6ce8\u610f:\u4e0a\u4f20\u7684\u9644\u4ef6\uff0c\u5fc5\u987b\u548c\u53d1\u7248\u7c7b\u578b\u4e00\u81f4\uff0c\u4e0d\u80fd\u6df7\u5408\u5176\u5b83\u7c7b\u578b ,\u4e0a\u4f20\u7684\u9644\u4ef6\u4e0d\u8981\u6709\u4e2d\u6587\u548c\u7279\u6b8a\u7b26\u53f7', upload_to='./update/%Y%m%d', verbose_name='\u9644\u4ef6')),
                ('shenqing', models.CharField(blank=True, default='0', help_text='\n        \u503c\u4e3a0\uff0c\u8868\u793a\u6ca1\u6709\u7533\u8bf7\n        \u503c\u4e3a1\uff0c\u8868\u793a\u7533\u8bf7\n        ..2,  \u5df2\u786e\u8ba4\n        ..3, \u5df2\u53d1\u7248\n        ..4, \u5df2\u56de\u6eda\n\n    ', max_length=1, null=True)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('shijiancuo', models.CharField(blank=True, default='1', max_length=30)),
                ('note', models.TextField(blank=True, help_text='\u9644\u52a0\u5907\u6ce8\u4fe1\u606f', null=True, verbose_name='\u5907\u6ce8')),
                ('shenhe2', models.CharField(blank=True, help_text='\u53d1\u7248\u5b8c\u540e\u7684\u5ba1\u6838\u6309\u94ae', max_length=11, verbose_name='\u5ba1\u6838\u6309\u94ae')),
                ('faban_types_id', models.ForeignKey(help_text='\u7528\u6237\u62e5\u6709\u7684\u53d1\u7248\u7c7b\u578b', on_delete=django.db.models.deletion.CASCADE, to='faban.faban_types', verbose_name='\u53d1\u7248\u7c7b\u578b')),
                ('faban_user', models.ForeignKey(help_text='\n    \u7ed1\u5b9a\u53d1\u7248\u7528\u6237\n    ', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u53d1\u7248\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u53d1\u7248\u4efb\u52a1',
                'verbose_name_plural': '\u53d1\u7248\u4efb\u52a1',
            },
        ),
        migrations.CreateModel(
            name='fu_faban_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u53d1\u7248\u7c7b\u578b', max_length=30, verbose_name='\u53d1\u7248\u7c7b\u578b')),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u53d1\u7248\u7c7b\u578b',
                'verbose_name_plural': '\u53d1\u7248\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='recipient_list_email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('user_id', models.OneToOneField(help_text='\u5173\u8054\u6536\u4ef6\u4eba\u90ae\u7bb1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7a0b\u5e8f\u6536\u4ef6\u4eba\u90ae\u7bb1',
                'verbose_name_plural': '\u7a0b\u5e8f\u6536\u4ef6\u4eba\u90ae\u7bb1',
            },
        ),
        migrations.CreateModel(
            name='yunwei_recipient_list_email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('user_id', models.OneToOneField(help_text='\u5173\u8054\u8fd0\u7ef4\u6536\u4ef6\u4eba\u90ae\u7bb1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u8fd0\u7ef4\u6536\u4ef6\u4eba\u90ae\u7bb1',
                'verbose_name_plural': '\u8fd0\u7ef4\u6536\u4ef6\u4eba\u90ae\u7bb1',
            },
        ),
        migrations.AddField(
            model_name='faban_types',
            name='fu_faban_type_ids',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faban.fu_faban_type', verbose_name='\u7236\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='extend_user_permissions',
            name='faban_types_many_id',
            field=models.ManyToManyField(to='faban.faban_types', verbose_name='\u5173\u8054\u90a3\u4e9b\u53d1\u7248\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='extend_user_permissions',
            name='recipient_list_email_id',
            field=models.ManyToManyField(to='faban.recipient_list_email', verbose_name='\u901a\u77e5\u7a0b\u5e8f\u90a3\u4e9b\u6536\u4ef6\u4eba'),
        ),
        migrations.AddField(
            model_name='extend_user_permissions',
            name='user_id',
            field=models.OneToOneField(help_text='\u6269\u5c55\u7528\u6237\u6743\u9650', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6269\u5c55\u7528\u6237\u6743\u9650'),
        ),
        migrations.AddField(
            model_name='extend_user_permissions',
            name='yunwei_recipient_list_email_id',
            field=models.ManyToManyField(to='faban.yunwei_recipient_list_email', verbose_name='\u901a\u77e5\u8fd0\u7ef4\u90a3\u4e9b\u6536\u4ef6\u4eba'),
        ),
    ]
