# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-17 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faban', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faban_upload',
            old_name='shenhe2',
            new_name='shenhe',
        ),
    ]
