# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-17 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faban', '0002_auto_20170317_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faban_upload',
            name='shenhe',
            field=models.CharField(blank=True, default='0', help_text='\u53d1\u7248\u5b8c\u540e\u7684\u5ba1\u6838\u6309\u94ae', max_length=11, verbose_name='\u5ba1\u6838\u6309\u94ae'),
        ),
    ]
