# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-20 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bumen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u90e8\u95e8', max_length=100, verbose_name='\u90e8\u95e8')),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u90e8\u95e8',
                'verbose_name_plural': '\u90e8\u95e8',
            },
        ),
        migrations.CreateModel(
            name='caozuo_leixing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u64cd\u4f5c\u7c7b\u578b', max_length=100, verbose_name='\u64cd\u4f5c\u7c7b\u578b')),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u64cd\u4f5c\u7c7b\u578b',
                'verbose_name_plural': '\u64cd\u4f5c\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='changku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='\u8bbe\u5907\u540d\u79f0', max_length=255, verbose_name='\u8bbe\u5907\u540d\u79f0')),
                ('xuliehao', models.CharField(blank=True, help_text='\u8bbe\u5907\u5e8f\u5217\u53f7', max_length=255, verbose_name='\u8bbe\u5907\u5e8f\u5217\u53f7')),
                ('zhuji_name', models.CharField(blank=True, help_text='\u4e3b\u673a\u540d', max_length=255, verbose_name='\u4e3b\u673a\u540d')),
                ('ip_address', models.CharField(blank=True, help_text='IP\u5730\u5740', max_length=255, verbose_name='IP\u5730\u5740')),
                ('cpu', models.CharField(blank=True, help_text='CPU', max_length=255, verbose_name='CPU')),
                ('neicun', models.CharField(blank=True, help_text='\u5185\u5b58', max_length=255, verbose_name='\u5185\u5b58')),
                ('xitong', models.CharField(blank=True, help_text='\u7cfb\u7edf', max_length=255, verbose_name='\u7cfb\u7edf')),
                ('zhuban', models.CharField(blank=True, help_text='\u4e3b\u677f', max_length=255, verbose_name='\u4e3b\u677f')),
                ('zhenlieka', models.CharField(blank=True, help_text='\u9635\u5217\u5361', max_length=255, verbose_name='\u9635\u5217\u5361')),
                ('yingpan', models.CharField(blank=True, help_text='\u786c\u76d8', max_length=255, verbose_name='\u786c\u76d8')),
                ('caigou_riqi', models.DateField(blank=True, help_text='\u91c7\u8d2d\u65e5\u671f', max_length=255, verbose_name='\u91c7\u8d2d\u65e5\u671f')),
                ('caigou_shuliang', models.CharField(blank=True, help_text='\u91c7\u8d2d\u6570\u91cf', max_length=255, verbose_name='\u91c7\u8d2d\u6570\u91cf')),
                ('lingyongren', models.CharField(blank=True, help_text='\u9886\u7528\u4eba', max_length=255, verbose_name='\u9886\u7528\u4eba')),
                ('lingyong_riq1', models.DateField(blank=True, help_text='\u9886\u7528\u65e5\u671f', max_length=255, verbose_name='\u9886\u7528\u65e5\u671f')),
                ('guihuan_riq', models.DateField(blank=True, help_text='\u5f52\u8fd8\u65e5\u671f', max_length=255, verbose_name='\u5f52\u8fd8\u65e5\u671f')),
                ('beizhu', models.TextField(blank=True, help_text='\u5907\u6ce8', verbose_name='\u5907\u6ce8')),
                ('bumen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zichanguanli.bumen')),
                ('caozuo_lexing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zichanguanli.caozuo_leixing')),
            ],
            options={
                'verbose_name': '\u8bbe\u5907\u4ed3\u5e93',
                'verbose_name_plural': '\u8bbe\u5907\u4ed3\u5e93',
            },
        ),
        migrations.CreateModel(
            name='shebei_leixing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u8bbe\u5907\u7c7b\u578b', max_length=100, verbose_name='\u8bbe\u5907\u7c7b\u578b')),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u8bbe\u5907\u7c7b\u578b',
                'verbose_name_plural': '\u8bbe\u5907\u7c7b\u578b',
            },
        ),
        migrations.AddField(
            model_name='changku',
            name='shebei_leixing_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zichanguanli.shebei_leixing'),
        ),
    ]
