# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-20 13:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zichanguanli', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changku',
            name='create_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 1, 20, 13, 2, 10, 725000)),
            preserve_default=False,
        ),
    ]
