# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-20 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zichanguanli', '0002_changku_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changku',
            name='caigou_riqi',
            field=models.DateField(blank=True, help_text='\u91c7\u8d2d\u65e5\u671f', max_length=255, null=True, verbose_name='\u91c7\u8d2d\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='changku',
            name='caozuo_lexing_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zichanguanli.caozuo_leixing', verbose_name='\u64cd\u4f5c\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='changku',
            name='guihuan_riq',
            field=models.DateField(blank=True, help_text='\u5f52\u8fd8\u65e5\u671f', max_length=255, null=True, verbose_name='\u5f52\u8fd8\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='changku',
            name='lingyong_riq1',
            field=models.DateField(blank=True, help_text='\u9886\u7528\u65e5\u671f', max_length=255, null=True, verbose_name='\u9886\u7528\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='changku',
            name='shebei_leixing_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zichanguanli.shebei_leixing', verbose_name='\u8bbe\u5907\u7c7b\u578b'),
        ),
    ]
