# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-13 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zichanguanli', '0003_auto_20170120_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changku',
            name='bumen_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zichanguanli.bumen', verbose_name='\u90e8\u95e8'),
        ),
    ]
