# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-21 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zichanguanli', '0004_auto_20170313_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='feiyong_leixing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u8d39\u7528\u540d\u79f0', max_length=255, verbose_name='\u8d39\u7528\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u8d39\u7528\u7c7b\u578b',
                'verbose_name_plural': '\u8d39\u7528\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='fufei_fangshi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u4ed8\u8d39\u65b9\u5f0f', max_length=255, verbose_name='\u4ed8\u8d39\u65b9\u5f0f')),
            ],
            options={
                'verbose_name': '\u4ed8\u8d39\u65b9\u5f0f',
                'verbose_name_plural': '\u4ed8\u8d39\u65b9\u5f0f',
            },
        ),
        migrations.CreateModel(
            name='qingkuan_mingxi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u8bf7\u6b3e\u540d\u79f0')),
                ('zhifu_jine_fanwei', models.CharField(max_length=255, verbose_name='\u652f\u4ed8\u91d1\u989d\u8303\u56f4')),
                ('shifou_qianding_hetong', models.CharField(max_length=255, verbose_name='\u662f\u5426\u7b7e\u8ba2\u5408\u540c')),
                ('yongtu', models.CharField(max_length=255, verbose_name='\u7528\u9014')),
                ('note', models.TextField(verbose_name='\u5907\u6ce8')),
                ('feiyong_leixing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zichanguanli.feiyong_leixing', verbose_name='\u8d39\u7528\u7c7b\u578b')),
                ('fufei_fangshi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zichanguanli.fufei_fangshi', verbose_name='\u4ed8\u8d39\u65b9\u5f0f')),
            ],
            options={
                'verbose_name': '\u8bf7\u6b3e\u660e\u7ec6',
                'verbose_name_plural': '\u8bf7\u6b3e\u660e\u7ec6',
            },
        ),
    ]
