# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-29 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zichanguanli', '0006_auto_20170322_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='guishu_bumen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u6700\u7ec8\u5f52\u5c5e\u90e8\u95e8')),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='zuzhuang_taishi_diannao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u8d44\u4ea7\u540d\u79f0')),
                ('xinghao', models.CharField(blank=True, max_length=255, verbose_name='\u8d44\u4ea7\u578b\u53f7')),
                ('jixing_fenlei', models.CharField(blank=True, max_length=255, verbose_name='\u673a\u578b\u5206\u7c7b')),
                ('zichan_bianma', models.CharField(blank=True, max_length=255, verbose_name='\u8d44\u4ea7\u7f16\u7801')),
                ('zichan_shiyongzhe', models.CharField(blank=True, max_length=255, verbose_name='\u8d44\u4ea7\u4f7f\u7528\u8005')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('zichan_yuanguishubumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zichanguanli.bumen', verbose_name='\u8d44\u4ea7\u539f\u5f52\u5c5e\u90e8\u95e8')),
                ('zichan_zuizhongguishubumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zichanguanli.guishu_bumen', verbose_name='\u8d44\u4ea7\u6700\u7ec8\u5f52\u5c5e\u90e8\u95e8')),
            ],
            options={
                'verbose_name': '\u7ec4\u88c5\u53f0\u5f0f\u7535\u8111',
                'verbose_name_plural': '\u7ec4\u88c5\u53f0\u5f0f\u7535\u8111',
            },
        ),
        migrations.AlterField(
            model_name='qingkuan_mingxi',
            name='jiage_danwei',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u4ef7\u683c\u5355\u4f4d'),
        ),
    ]
