# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0003_auto_20170301_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '\u4efb\u52a1', 'verbose_name_plural': '\u4efb\u52a1'},
        ),
        migrations.AddField(
            model_name='zhuji_duankou',
            name='url_address',
            field=models.CharField(default=1, max_length=255, verbose_name='url\u5730\u5740'),
            preserve_default=False,
        ),
    ]
