# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-02 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0004_auto_20170301_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhuji_duankou',
            name='jiaoben',
            field=models.CharField(default=1, max_length=255, verbose_name='\u811a\u672c\u7edd\u5bf9\u8def\u5f84'),
            preserve_default=False,
        ),
    ]
