# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-25 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logcaiji', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cpuload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, verbose_name='\u4e3b\u673a\u540d\u5b57')),
                ('one', models.CharField(max_length=50, verbose_name='1\u5206\u949f')),
                ('five', models.CharField(max_length=50, verbose_name='5\u5206\u949f')),
                ('fifteen', models.CharField(max_length=50, verbose_name='15\u5206\u949f')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cpuload',
                'verbose_name_plural': 'cpuload',
            },
        ),
    ]
