# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-11 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='ip')),
                ('name', models.CharField(max_length=255, verbose_name='\u4e3b\u673a\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='jifang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u673a\u623f')),
            ],
        ),
        migrations.CreateModel(
            name='shijian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u4e8b\u4ef6\u540d\u79f0')),
                ('value', models.CharField(max_length=255, verbose_name='\u4e8b\u4ef6\u503c')),
                ('bind_host', models.ManyToManyField(to='new_webshell.host', verbose_name='\u4e3b\u673a\u4e8b\u4ef6\u7ed1\u5b9a')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='jifang_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_webshell.jifang', verbose_name='\u7ed1\u5b9a\u673a\u623f'),
        ),
    ]
