# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-11 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_webshell', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shijian',
            name='bind_host',
        ),
        migrations.AddField(
            model_name='host',
            name='bind_shijian',
            field=models.ManyToManyField(to='new_webshell.shijian', verbose_name='\u4e3b\u673a\u4e8b\u4ef6\u7ed1\u5b9a'),
        ),
    ]
