# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-02 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_webshell', '0002_auto_20170611_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='host_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u4e3b\u673a\u7c7b\u578b')),
                ('jifang_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_webshell.jifang', verbose_name='\u5173\u8054\u673a\u623f')),
            ],
        ),
        migrations.CreateModel(
            name='shijian_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u4e8b\u4ef6\u65e5\u5fd7\u5bf9\u5e94\u7684UUID')),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='host',
            name='jifang_id',
        ),
        migrations.AddField(
            model_name='shijian_log',
            name='host_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_webshell.host', verbose_name='\u5173\u8054\u4e3b\u673a'),
        ),
        migrations.AddField(
            model_name='shijian_log',
            name='shijian_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_webshell.shijian', verbose_name='\u5173\u8054\u4e8b\u4ef6'),
        ),
        migrations.AddField(
            model_name='host',
            name='host_type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='new_webshell.host_type', verbose_name='\u5173\u8054\u4e3b\u673a\u7c7b\u578b'),
            preserve_default=False,
        ),
    ]
