# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-02 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_webshell', '0003_auto_20170702_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name': '\u4e3b\u673a', 'verbose_name_plural': '\u4e3b\u673a'},
        ),
        migrations.AlterModelOptions(
            name='host_type',
            options={'verbose_name': '\u4e3b\u673a\u7c7b\u578b', 'verbose_name_plural': '\u4e3b\u673a\u7c7b\u578b'},
        ),
        migrations.AlterModelOptions(
            name='jifang',
            options={'verbose_name': '\u673a\u623f', 'verbose_name_plural': '\u673a\u623f'},
        ),
        migrations.AlterModelOptions(
            name='shijian',
            options={'verbose_name': '\u4e8b\u4ef6', 'verbose_name_plural': '\u4e8b\u4ef6'},
        ),
        migrations.AlterModelOptions(
            name='shijian_log',
            options={'verbose_name': '\u4e3b\u673a\u4e8b\u4ef6\u65e5\u5fd7', 'verbose_name_plural': '\u4e3b\u673a\u4e8b\u4ef6\u65e5\u5fd7'},
        ),
        migrations.AddField(
            model_name='host_type',
            name='url',
            field=models.URLField(default=1, verbose_name='\u5bfc\u822aurl'),
            preserve_default=False,
        ),
    ]
