FROM debian:jessie
LABEL maintainer "dongxu2@meilele.com"

# 软件版本
ENV PHP_VERSION 7.1.8
ENV NGINX_VERSION 1.12.1
ENV LIBMEMCACHED_VERSION 1.0.18
ENV MEMCACHED_VERSION 3.0.3
ENV YAR_VERSION 2.0.3
ENV XHPROF_VERSION 0.9.5
ENV AMQP_VERSION 1.9.1
ENV MONGODB_VERSION 1.2.9

# 编译工具
ENV BUILD_TOOLS m4 \
                autoconf \
                autoconf2.13 \
                openssl \
                wget \
                gcc \
                make \
                pkg-config \
                g++ 
# 依赖
ENV BUILD_DEPS  build-essential \
                libtool \
                bison \
                re2c \
                libcurl4-gnutls-dev \
                libxml2-dev \
                zlib1g-dev \
                libpcre3-dev \
                libjpeg-dev \
                libpng12-dev \
                libfreetype6-dev \
                libmhash-dev \
                libmcrypt-dev \
                libssl-dev \
                libpcre3-dev \
                libldap2-dev \
                libsasl2-dev \
                libmysqlclient-dev \
                librabbitmq-dev 
               

# php和nginx安装路径
ENV PHP_LOCATION /usr/local/php
ENV NGINX_LOCATION /usr/local/nginx

# php编译参数
ENV PHP_BUILD_ARG   --prefix=${PHP_LOCATION} \
                    --with-config-file-path=${PHP_LOCATION}/etc \
                    --enable-bcmath \
                    --with-pdo_sqlite \
                    --with-gettext \
                    --with-iconv \
                    --enable-ftp \
                    --with-sqlite3 \
                    --enable-mbstring \
                    --enable-sockets \
                    --enable-zip \
                    --enable-soap \
                    --enable-phar \
                    --with-openssl \
                    --with-zlib \
                    --with-curl \
                    --with-gd \
                    --with-jpeg-dir \
                    --with-png-dir \
                    --with-freetype-dir \
                    --with-mcrypt \
                    --with-mhash \
                    --with-ldap \
                    --with-ldap-sasl \
                    --with-mysqli=mysqlnd \
                    --with-pdo-mysql=mysqlnd \
                    --with-pear \
                    --with-libdir=lib64 \
                    --enable-calendar \
                    --enable-opcache \
                    --disable-cgi \
                    --enable-cli \
                    --enable-fpm \
                    --with-fpm-user=www-data \
                    --with-fpm-group=www-data
# nginx编译参数 
ENV nginx_BUILD_ARG --prefix=${NGINX_LOCATION} \
                    --with-pcre \
                    --with-zlib \
                    --with-http_ssl_module \
                    --with-openssl
#替换源
COPY sources.list /etc/apt/sources.list

# 工作目录
ENV SRC_DIR /opt/soft
WORKDIR ${SRC_DIR}

# 复制软件
COPY ./soft ${SRC_DIR}

# 开始编译安装
RUN apt-get update \
    && apt-get -y --no-install-recommends install ${BUILD_DEPS} ${BUILD_TOOLS} \

# 编译php
    && tar xf php-${PHP_VERSION}.tar.gz \
    && cd php-${PHP_VERSION} \
    && ln -s /usr/lib/x86_64-linux-gnu/libssl.so /usr/lib/libssl.so \
    && ln -s /usr/lib/x86_64-linux-gnu/libldap.so /usr/lib/libldap.so \
    && ln -s /usr/lib/x86_64-linux-gnu/liblber.so /usr/lib/liblber.so \
    && ln -s /usr/lib /usr/lib64 \
    && ./configure ${PHP_BUILD_ARG} \
    && make -j$(nproc) \
    && make install \

    && cd ${SRC_DIR} \
    && tar zxvf amqp-${AMQP_VERSION}.tgz \
    && cd amqp-${AMQP_VERSION} \
    && ${PHP_LOCATION}/bin/phpize \
    && ./configure --with-php-config=${PHP_LOCATION}/bin/php-config --with-amqp \
    && make -j$(nproc) \
    && make install \

    && cd ${SRC_DIR} \
    && tar zxvf yar-${YAR_VERSION}.tgz \
    && cd yar-${YAR_VERSION} \
    && ${PHP_LOCATION}/bin/phpize \
    && ./configure --with-php-config=${PHP_LOCATION}/bin/php-config \
    && make -j$(nproc) \
    && make install \

    && cd ${SRC_DIR} \
    && tar zxvf libmemcached-${LIBMEMCACHED_VERSION}.tar.gz \
    && cd libmemcached-${LIBMEMCACHED_VERSION} \
    && ./configure --prefix=/usr/local/libmemcached --with-memcached \
    && make -j$(nproc) \
    && make install \

    && cd ${SRC_DIR} \
    && tar zxvf memcached-${MEMCACHED_VERSION}.tgz \
    && cd memcached-${MEMCACHED_VERSION} \
    && ${PHP_LOCATION}/bin/phpize \
    && ./configure --enable-memcached --with-php-config=${PHP_LOCATION}/bin/php-config --with-zlib-dir --with-libmemcached-dir=/usr/local/libmemcached --prefix=/usr/local/phpmemcached  --disable-memcached-sasl \
    && make -j$(nproc) \
    && make install \

    && cd ${SRC_DIR} \
    && tar zxvf xhprof-${XHPROF_VERSION}.tar.gz \
    && cd phpng-xhprof \
    && ${PHP_LOCATION}/bin/phpize \
    && ./configure --with-php-config=${PHP_LOCATION}/bin/php-config \
    && make -j$(nproc) \
    && make install \

    && cd ${SRC_DIR} \
    && tar zxvf mongodb-${MONGODB_VERSION}.tgz \
    && cd mongodb-${MONGODB_VERSION} \
    && ${PHP_LOCATION}/bin/phpize \
    && ./configure --with-php-config=${PHP_LOCATION}/bin/php-config \
    && make -j$(nproc) \
    && make install \

# 编译nginx
    && cd ${SRC_DIR} \
    && tar xf nginx-${NGINX_VERSION}.tar.gz \
    && cd nginx-${NGINX_VERSION} \
    && ./configure ${NGINX_BUILD_ARG} \
    && make -j$(nproc) \
    && make install \

# 清理
    && apt-get purge -y --auto-remove ${BUILD_TOOLS} \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf ${SRC_DIR} 

# 复制php和nginx配置文件
COPY ./conf/php/php.ini ${PHP_LOCATION}/etc/php.ini
COPY ./conf/php/php-fpm.conf ${PHP_LOCATION}/etc/php-fpm.conf
COPY ./conf/nginx/nginx.conf ${NGINX_LOCATION}/conf/nginx.conf

COPY ./site ${NGINX_LOCATION}/html

# 定义启动容器时运行的命令
CMD /usr/local/nginx/sbin/nginx && /usr/local/php/sbin/php-fpm

#端口映射
EXPOSE 80