#coding=utf-8
from __future__ import unicode_literals
"""
Django settings for cmdb project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'a+nfxve!auzx7vew2x59s#+s-$2d@%%i7qvn+!frky+yruf+k7'

# SECURITY WARNING: don't run with debug turned on in production!
if not os.name == 'nt':
    DEBUG = True
    ALLOWED_HOSTS = ['*']
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'cmdb',
            'USER': 'admin',
            'PASSWORD': 'wanwan',
            'HOST': '192.168.0.17',
            'PORT': '3306',
        }
    }
else:
    DEBUG = True
    ALLOWED_HOSTS = []
    DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'testcmdb',
        'USER': 'admin',
        'PASSWORD': 'wanwan',
        'HOST': '192.168.0.17',
        'PORT': '3306',
       # 'CONN_MAX_AGE':None
    }
}


# Application definition

INSTALLED_APPS = [
    'suit',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
  'rongqi',
 'vhost',
   'baoleiji',
    'idc',
    'suit_redactor',
    'suit_ckeditor',
    'weixin',
    'gongdan',
    'zichanguanli',
    'faban',
    'faillog',
    #'pyinotifys',
    'baishi',
    'logcaiji',
    'new_webshell',
    'dockermanageplatform',
    'online_logs_download'

]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cmdb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [r'D:\svn\wanhaifeng\python_projects\cmdb\dockermanageplatform\templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'cmdb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases




# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'



USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/usr/local/nginx_1.10.2/html/static'
#邮件全局设置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_USE_SSL  = False
EMAIL_HOST = "mail.meilele.com"
EMAIL_PORT = 25
EMAIL_HOST_USER = "it"
EMAIL_HOST_PASSWORD = "mll123456@"
DEFAULT_FROM_EMAIL = "it@meilele.com"

SUIT_CONFIG = {
    'LIST_PER_PAGE': 15,
    'ADMIN_NAME' :"运维资源管理后台",
    'MENU':(
       'auth',
#        {'label':'添加家长学生','models':
#            ('baishi.kaohao','baishi.banji','baishi.jiazhang',
#             'baishi.xuesheng',"baishi.piliang_xuesheng_jiazhang_daoru") },
#
# {'label':'成绩表和批量导入','models':
#            ('baishi.chengjibiao','baishi.type_chengji','baishi.piliang_daoru') },




        'faban',
        'dockermanageplatform',
       'online_logs_download',
         'new_webshell',
        'faillog',
        'rongqi',
        'weixin',
        'vhost',
       # 'zichanguanli',
       {'label': '资产管理参数', 'models':
           ('zichanguanli.shebei_leixing', 'zichanguanli.caozuo_leixing', 'zichanguanli.bumen',
            'zichanguanli.feiyong_leixing','zichanguanli.guishu_bumen')},
        {'label': '资产管理录入', 'models':
           ('zichanguanli.changku', 'zichanguanli.zuzhuang_taishi_diannao')},
        {'label': '资产管理请款明细', 'models':
           ('zichanguanli.fufei_fangshi','zichanguanli.qingkuan_mingxi')},



    )



}

