# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-12 11:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bind_users_hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateTimeField(auto_created=True)),
                ('user_alias', models.CharField(blank=True, help_text='\u7528\u6237\u522b\u540d', max_length=50)),
            ],
            options={
                'verbose_name': '\u7ed1\u5b9a\u7528\u6237\u548c\u4e3b\u673a',
                'verbose_name_plural': '\u7ed1\u5b9a\u7528\u6237\u548c\u4e3b\u673a',
            },
        ),
        migrations.CreateModel(
            name='hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateTimeField(auto_created=True)),
                ('hostname', models.CharField(help_text='\u4e3b\u673a\u540d', max_length=100)),
                ('hostip', models.GenericIPAddressField(help_text='\u4e3b\u673aip,\u5fc5\u987b\u552f\u4e00', unique=True)),
                ('hostuser', models.CharField(help_text='\u4e3b\u673a\u7528\u6237', max_length=50)),
                ('hostspassword', models.CharField(help_text='\u4e3b\u673a\u5bc6\u7801', max_length=32)),
            ],
            options={
                'verbose_name': '\u8fdc\u7a0b\u4e3b\u673a',
                'verbose_name_plural': '\u8fdc\u7a0b\u4e3b\u673a',
            },
        ),
        migrations.CreateModel(
            name='idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateTimeField(auto_created=True, help_text='\u521b\u5efa\u65f6\u95f4')),
                ('jifang', models.CharField(help_text='\u673a\u623f\u73af\u5883,\u6df1\u5733\u673a\u623f\uff0c\u6210\u90fd\u673a\u623f', max_length=100)),
            ],
            options={
                'verbose_name': 'IDC',
                'verbose_name_plural': 'IDC',
            },
        ),
        migrations.CreateModel(
            name='shenji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateTimeField(auto_created=True)),
                ('username', models.CharField(help_text='\u8bb0\u5f55\u7528\u6237', max_length=50)),
                ('hostip', models.CharField(help_text='\u8bb0\u5f55\u64cd\u4f5c\u7684\u4e3b\u673aip', max_length=50)),
                ('host_cmd', models.CharField(help_text='\u8bb0\u5f55\u64cd\u4f5c\u7684\u6307\u4ee4', max_length=255)),
            ],
            options={
                'verbose_name': '\u5ba1\u8ba1\u4fe1\u606f',
                'verbose_name_plural': '\u5ba1\u8ba1\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='hosts',
            name='idc_id',
            field=models.ForeignKey(help_text='\u4e3b\u673a\u5f52\u5c5e\u90a3\u4e2a\u673a\u623f', on_delete=django.db.models.deletion.CASCADE, to='baoleiji.idc'),
        ),
        migrations.AddField(
            model_name='bind_users_hosts',
            name='hosts_id',
            field=models.ManyToManyField(help_text='\u7528\u6237\u548c\u4e3b\u673a\u7684\u591a\u5bf9\u591a\u5173\u7cfb', to='baoleiji.hosts'),
        ),
        migrations.AddField(
            model_name='bind_users_hosts',
            name='user_id',
            field=models.OneToOneField(help_text='\u5bf9\u5e94\u7684\u771f\u5b9e\u7528\u6237', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
