# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-12 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baoleiji', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bind_users_hosts',
            name='createdate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='createdate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='idc',
            name='createdate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shenji',
            name='createdate',
            field=models.DateField(auto_now=True),
        ),
    ]
