# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-12 16:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baoleiji', '0002_auto_20161212_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosts',
            name='hostport',
            field=models.IntegerField(default=22),
        ),
        migrations.AlterField(
            model_name='bind_users_hosts',
            name='hosts_id',
            field=models.ManyToManyField(help_text='\u7528\u6237\u548c\u4e3b\u673a\u7684\u591a\u5bf9\u591a\u5173\u7cfb', to='baoleiji.hosts', verbose_name='\u7528\u6237\u4e3b\u673a'),
        ),
        migrations.AlterField(
            model_name='bind_users_hosts',
            name='user_alias',
            field=models.CharField(blank=True, help_text='\u7528\u6237\u522b\u540d', max_length=50, verbose_name='\u7528\u6237\u522b\u540d'),
        ),
        migrations.AlterField(
            model_name='bind_users_hosts',
            name='user_id',
            field=models.OneToOneField(help_text='\u5bf9\u5e94\u7684\u771f\u5b9e\u7528\u6237', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u771f\u5b9e\u7528\u6237'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='hostip',
            field=models.GenericIPAddressField(help_text='\u4e3b\u673aip,\u5fc5\u987b\u552f\u4e00', unique=True, verbose_name='\u4e3b\u673aIP'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='hostname',
            field=models.CharField(help_text='\u4e3b\u673a\u540d', max_length=100, verbose_name='\u4e3b\u673a\u540d'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='hostspassword',
            field=models.CharField(help_text='\u4e3b\u673a\u5bc6\u7801', max_length=32, verbose_name='\u4e3b\u673a\u5bc6\u7801'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='hostuser',
            field=models.CharField(help_text='\u4e3b\u673a\u7528\u6237', max_length=50, verbose_name='\u4e3b\u673a\u7528\u6237'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='idc_id',
            field=models.ForeignKey(help_text='\u4e3b\u673a\u5f52\u5c5e\u90a3\u4e2a\u673a\u623f', on_delete=django.db.models.deletion.CASCADE, to='baoleiji.idc', verbose_name='IDC\u673a\u623f'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='jifang',
            field=models.CharField(help_text='\u673a\u623f\u73af\u5883,\u6df1\u5733\u673a\u623f\uff0c\u6210\u90fd\u673a\u623f', max_length=100, unique=True, verbose_name='IDC\u673a\u623f'),
        ),
        migrations.AlterField(
            model_name='shenji',
            name='host_cmd',
            field=models.CharField(help_text='\u8bb0\u5f55\u64cd\u4f5c\u7684\u6307\u4ee4', max_length=255, verbose_name='\u6307\u4ee4'),
        ),
        migrations.AlterField(
            model_name='shenji',
            name='hostip',
            field=models.CharField(help_text='\u8bb0\u5f55\u64cd\u4f5c\u7684\u4e3b\u673aip', max_length=50, verbose_name='\u4e3b\u673aIP'),
        ),
        migrations.AlterField(
            model_name='shenji',
            name='username',
            field=models.CharField(help_text='\u8bb0\u5f55\u7528\u6237', max_length=50, verbose_name='\u7528\u6237'),
        ),
    ]
