# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-29 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baoleiji', '0005_mulu_sfile_dfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='gongong_shell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bieming', models.CharField(max_length=255, verbose_name='\u522b\u540d')),
                ('mulu', models.CharField(max_length=255, verbose_name='\u76ee\u5f55')),
                ('sfile', models.CharField(max_length=255, verbose_name='\u6e90\u6587\u4ef6')),
                ('dfile', models.CharField(max_length=255, verbose_name='\u76ee\u6807\u6587\u4ef6')),
                ('createdate', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u516c\u5171shell\u76ee\u5f55\u6587\u4ef6',
                'verbose_name_plural': '\u516c\u5171shell\u76ee\u5f55\u6587\u4ef6',
            },
        ),
    ]
