# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-29 14:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baoleiji', '0006_gongong_shell'),
    ]

    operations = [
        migrations.AddField(
            model_name='mulu_sfile_dfile',
            name='createuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7ed1\u5b9a\u7528\u6237'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gongong_shell',
            name='mulu',
            field=models.CharField(help_text='\u6b64\u5904\u662f\u76ee\u6807\u76ee\u5f55', max_length=255, verbose_name='\u76ee\u6807\u76ee\u5f55'),
        ),
        migrations.AlterField(
            model_name='mulu_sfile_dfile',
            name='mulu',
            field=models.CharField(help_text='\u6b64\u5904\u662f\u76ee\u6807\u76ee\u5f55', max_length=255, verbose_name='\u76ee\u6807\u76ee\u5f55'),
        ),
    ]
