# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-30 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baoleiji', '0007_auto_20161229_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gongong_shell',
            name='sfile',
            field=models.CharField(max_length=255, unique=True, verbose_name='\u6e90\u6587\u4ef6'),
        ),
    ]
