# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 13:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='guanli_vhost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '\u7ba1\u7406\u865a\u62df\u4e3b\u673a',
                'verbose_name_plural': '\u7ba1\u7406\u865a\u62df\u4e3b\u673a',
            },
        ),
        migrations.CreateModel(
            name='idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', '\u5f00\u53d1\u73af\u5883'), ('2', '\u6d4b\u8bd5\u73af\u5883'), ('3', '\u7ebf\u4e0a\u73af\u5883')], max_length=20, unique=True, verbose_name='IDC\u73af\u5883')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'IDC\u73af\u5883',
                'verbose_name_plural': 'IDC\u73af\u5883',
            },
        ),
        migrations.CreateModel(
            name='ipaddress_vhost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('is_enable', models.BooleanField(default=False, help_text='\u9ed8\u8ba4\u4e3aFalse\uff0c\u4ee3\u8868\u53ef\u4ee5\u5b9e\u7528')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u7684\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6dfb\u52a0\u865a\u62df\u4e3b\u673aIP',
                'verbose_name_plural': '\u6dfb\u52a0\u865a\u62df\u4e3b\u673aIP',
            },
        ),
        migrations.CreateModel(
            name='shenqing_vhost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shenqing_mingzi', models.CharField(help_text='\u7533\u8bf7\u865a\u62df\u4e3b\u673a\u7684\u540d\u79f0', max_length=100, verbose_name='\u7533\u8bf7\u865a\u62df\u4e3b\u673a\u540d\u79f0')),
                ('type_apps', models.CharField(choices=[('1', 'mysql'), ('2', 'redis'), ('3', 'mongodb'), ('4', 'zookeeper')], max_length=20, verbose_name='\u5e94\u7528\u7c7b\u578b')),
                ('note', models.CharField(blank=True, help_text='\u586b\u5199\u989d\u5916\u7684\u4fe1\u606f', max_length=255, null=True, verbose_name='\u5907\u6ce8')),
                ('shenqing_status', models.CharField(choices=[('1', '\u7533\u8bf7\u63d0\u4ea4'), ('2', '\u7533\u8bf7\u6210\u529f'), ('3', '\u7533\u8bf7\u5931\u8d25'), ('4', '\u672a\u7533\u8bf7')], default='4', max_length=1, verbose_name='\u7533\u8bf7\u72b6\u6001')),
                ('use_flag', models.IntegerField(default=1, verbose_name='\u903b\u8f91\u5220\u9664\u6807\u8bc6')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u7684\u65f6\u95f4')),
                ('end_date', models.DateField(help_text='\u957f\u65f6\u95f4\u7528\uff0c\u9009\u62e9\u4e00\u4e2a\u957f\u4e00\u70b9\u7684\u65f6\u95f4\u5427', verbose_name='\u865a\u62df\u4e3b\u673a\u4f7f\u7528\u7ed3\u675f\u65f6\u95f4')),
                ('type_idc_id', models.ForeignKey(help_text='\u9009\u62e9\u4e00\u4e2a\u73af\u5883', on_delete=django.db.models.deletion.CASCADE, to='vhost.idc', verbose_name='\u865a\u62df\u4e3b\u673a\u73af\u5883')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237id')),
            ],
            options={
                'verbose_name': '\u7533\u8bf7\u865a\u62df\u4e3b\u673a',
                'verbose_name_plural': '\u7533\u8bf7\u865a\u62df\u4e3b\u673a',
            },
        ),
        migrations.AddField(
            model_name='guanli_vhost',
            name='shenqing_rongqi_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vhost.shenqing_vhost', verbose_name='\u7533\u8bf7\u865a\u62df\u4e3b\u673a\u7684ID'),
        ),
        migrations.AddField(
            model_name='guanli_vhost',
            name='vhost_ip',
            field=models.OneToOneField(help_text='\u586b\u5199\u865a\u62df\u4e3b\u673a\u7684\u5916\u90e8ip\u5730\u5740', on_delete=django.db.models.deletion.CASCADE, to='vhost.ipaddress_vhost', verbose_name='\u865a\u62df\u4e3b\u673a\u7ed1\u5b9a\u7684IP'),
        ),
    ]
