# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idc',
            name='type',
            field=models.CharField(choices=[('\u5f00\u53d1\u73af\u5883', '\u5f00\u53d1\u73af\u5883'), ('\u6d4b\u8bd5\u73af\u5883', '\u6d4b\u8bd5\u73af\u5883'), ('\u7ebf\u4e0a\u73af\u5883', '\u7ebf\u4e0a\u73af\u5883')], max_length=20, unique=True, verbose_name='IDC\u73af\u5883'),
        ),
    ]
