# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhost', '0002_auto_20161117_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shenqing_vhost',
            name='type_apps',
            field=models.CharField(choices=[('mysql', 'mysql'), ('redis', 'redis'), ('mongodb', 'mongodb'), ('zookeeper', 'zookeeper')], max_length=20, verbose_name='\u5e94\u7528\u7c7b\u578b'),
        ),
    ]
