# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vhost', '0003_auto_20161117_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='guanli_vhost',
            name='login_pass',
            field=models.CharField(blank=True, default='123456', max_length=32, null=True, verbose_name='\u767b\u5f55\u5bc6\u7801'),
        ),
        migrations.AddField(
            model_name='guanli_vhost',
            name='login_user',
            field=models.CharField(blank=True, default='root', max_length=20, null=True, verbose_name='\u767b\u5f55\u8d26\u6237'),
        ),
        migrations.AlterField(
            model_name='guanli_vhost',
            name='shenqing_rongqi_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vhost.shenqing_vhost', verbose_name='\u4e3b\u673a\u7684ID'),
        ),
        migrations.AlterField(
            model_name='guanli_vhost',
            name='vhost_ip',
            field=models.OneToOneField(help_text='\u586b\u5199\u865a\u62df\u4e3b\u673a\u7684\u5916\u90e8ip\u5730\u5740', on_delete=django.db.models.deletion.CASCADE, to='vhost.ipaddress_vhost', verbose_name='\u4e3b\u673a\u7ed1\u5b9a\u7684IP'),
        ),
        migrations.AlterField(
            model_name='shenqing_vhost',
            name='end_date',
            field=models.DateField(help_text='\u957f\u65f6\u95f4\u7528\uff0c\u9009\u62e9\u4e00\u4e2a\u957f\u4e00\u70b9\u7684\u65f6\u95f4\u5427', verbose_name='\u4f7f\u7528\u7ed3\u675f\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='shenqing_vhost',
            name='shenqing_mingzi',
            field=models.CharField(help_text='\u7533\u8bf7\u865a\u62df\u4e3b\u673a\u7684\u540d\u79f0', max_length=100, verbose_name='\u4e3b\u673a\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='shenqing_vhost',
            name='type_idc_id',
            field=models.ForeignKey(help_text='\u9009\u62e9\u4e00\u4e2a\u73af\u5883', on_delete=django.db.models.deletion.CASCADE, to='vhost.idc', verbose_name='\u4e3b\u673a\u73af\u5883'),
        ),
    ]
