# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-18 09:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='guanli_rongqi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rongqi_id', models.CharField(max_length=100, unique=True, verbose_name='\u751f\u6210\u5bb9\u5668ID')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u7684\u65f6\u95f4')),
                ('external_directory', models.CharField(blank=True, help_text='\u771f\u5b9e\u670d\u52a1\u5668\u7684\u5b58\u653e\u8def\u5f84', max_length=30, null=True, verbose_name='\u5916\u90e8\u6302\u8f7d\u76d8')),
            ],
            options={
                'verbose_name': '\u7ba1\u7406\u5bb9\u5668',
                'verbose_name_plural': '\u7ba1\u7406\u5bb9\u5668',
            },
        ),
        migrations.CreateModel(
            name='ipaddress_rongqi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_name', models.CharField(choices=[(b'1', b'\xe7\xa0\x94\xe5\x8f\x91\xe9\x83\xa8\xe9\x97\xa8'), (b'2', b'\xe6\x9e\xb6\xe6\x9e\x84\xe9\x83\xa8\xe9\x97\xa8'), (b'3', b'\xe6\xb5\x8b\xe8\xaf\x95\xe9\x83\xa8\xe9\x97\xa8')], help_text='\u90e8\u95e8\u540d\u79f0,1->\u7814\u53d1\u90e8\u95e8 2->\u67b6\u6784\u90e8\u95e8 3->\u6d4b\u8bd5\u90e8\u95e8', max_length=50)),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('is_enable', models.BooleanField(default=False, help_text='\u9ed8\u8ba4\u5173\u95ed')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u7684\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6dfb\u52a0\u5bb9\u5668IP',
                'verbose_name_plural': '\u6dfb\u52a0\u5bb9\u5668IP',
            },
        ),
        migrations.CreateModel(
            name='pipaddress_rongqi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_name', models.CharField(max_length=50, verbose_name='Docker\u5bbf\u4e3b\u673a\u540d')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='Docker\u5bbf\u4e3b\u673aIP')),
                ('password', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u5bbf\u4e3b\u673a\u5bc6\u7801')),
                ('geteway', models.GenericIPAddressField(verbose_name='\u7f51\u5173')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u7684\u65f6\u95f4')),
            ],
            options={
                'verbose_name': 'Docker\u5bbf\u4e3b\u673a',
                'verbose_name_plural': 'Docker\u5bbf\u4e3b\u673a',
            },
        ),
        migrations.CreateModel(
            name='shenqing_rongqi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shenqing_mingzi', models.CharField(help_text='\u7533\u8bf7\u5bb9\u5668\u7684\u540d\u79f0', max_length=100, verbose_name='\u7533\u8bf7\u5bb9\u5668\u540d\u79f0')),
                ('shenqing_status', models.CharField(choices=[(b'1', b'\xe7\x94\xb3\xe8\xaf\xb7\xe6\x8f\x90\xe4\xba\xa4'), (b'2', b'\xe7\x94\xb3\xe8\xaf\xb7\xe6\x88\x90\xe5\x8a\x9f'), (b'3', b'\xe7\x94\xb3\xe8\xaf\xb7\xe5\xa4\xb1\xe8\xb4\xa5'), (b'4', b'\xe6\x9c\xaa\xe7\x94\xb3\xe8\xaf\xb7')], default=b'4', max_length=1, verbose_name='\u7533\u8bf7\u72b6\u6001')),
                ('use_flag', models.IntegerField(default=1, verbose_name='\u903b\u8f91\u5220\u9664\u6807\u8bc6')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u7684\u65f6\u95f4')),
                ('end_date', models.DateField(help_text='\u6b64\u9009\u9879\u5fc5\u586b', verbose_name='\u5bb9\u5668\u4f7f\u7528\u7ed3\u675f\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7533\u8bf7\u5bb9\u5668',
                'verbose_name_plural': '\u7533\u8bf7\u5bb9\u5668',
            },
        ),
        migrations.CreateModel(
            name='type_rongqi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rongqi_name', models.CharField(max_length=100, verbose_name='\u5bb9\u5668\u522b\u540d')),
                ('rongqi_type', models.CharField(max_length=100, verbose_name='\u4e3b\u5bb9\u5668\u7c7b\u578b')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u7684\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u4e3b\u5bb9\u5668\u7c7b\u578b',
                'verbose_name_plural': '\u4e3b\u5bb9\u5668\u7c7b\u578b',
            },
        ),
        migrations.AddField(
            model_name='shenqing_rongqi',
            name='type_rongqi_id',
            field=models.ForeignKey(help_text='\u9009\u62e9\u4e00\u4e2a\u7236\u5bb9\u5668', on_delete=django.db.models.deletion.CASCADE, to='rongqi.type_rongqi', verbose_name='\u7236\u5bb9\u5668'),
        ),
        migrations.AddField(
            model_name='shenqing_rongqi',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237id'),
        ),
        migrations.AddField(
            model_name='ipaddress_rongqi',
            name='pipaddress_rongqi_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rongqi.pipaddress_rongqi', verbose_name=b'Docker\xe5\xae\xbf\xe4\xb8\xbb\xe6\x9c\xba'),
        ),
        migrations.AddField(
            model_name='guanli_rongqi',
            name='rongqi_ip',
            field=models.OneToOneField(help_text='\u586b\u5199\u5bb9\u5668\u7684\u5916\u90e8ip\u5730\u5740', on_delete=django.db.models.deletion.CASCADE, to='rongqi.ipaddress_rongqi', verbose_name='\u5bb9\u5668\u7ed1\u5b9a\u7684IP'),
        ),
        migrations.AddField(
            model_name='guanli_rongqi',
            name='shenqing_rongqi_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rongqi.shenqing_rongqi', verbose_name='\u7533\u8bf7\u5bb9\u5668\u7684ID'),
        ),
    ]
