# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-18 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rongqi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_rongqi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_created=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('shenqing_id', models.IntegerField(help_text='\u8f93\u5165\u8ba2\u5355ID', verbose_name='\u7533\u8bf7ID')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5907\u6ce8')),
                ('ipaddress_rongqi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rongqi.ipaddress_rongqi', verbose_name='\u7ed1\u5b9aIP')),
            ],
        ),
    ]
