# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-28 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rongqi', '0003_auto_20161118_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guanli_rongqi',
            name='shenqing_rongqi_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rongqi.shenqing_rongqi', verbose_name='\u7533\u8bf7\u5bb9\u5668\u7684\u540d\u79f0'),
        ),
    ]
