# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-24 18:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='banji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u4f8b\u5b50:2016\u7ea7\u4e00\u73ed', max_length=255, unique=True, verbose_name='\u73ed\u7ea7')),
                ('Notes', models.TextField(blank=True, verbose_name='\u5907\u6ce8')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('laoshi', models.ManyToManyField(help_text='\u73ed\u7ea7\u4e0b\u7ed1\u5b9a\u90a3\u4e9b\u8001\u5e08', to=settings.AUTH_USER_MODEL, verbose_name='\u8001\u5e08')),
            ],
            options={
                'verbose_name': '\u73ed\u7ea7\u7ed1\u5b9a\u8001\u5e08',
                'verbose_name_plural': '\u73ed\u7ea7\u7ed1\u5b9a\u8001\u5e08',
            },
        ),
        migrations.CreateModel(
            name='chengjibiao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yuwen', models.CharField(blank=True, max_length=20, verbose_name='\u8bed\u6587')),
                ('shuxue', models.CharField(blank=True, max_length=20, verbose_name='\u6570\u5b66')),
                ('yingyu', models.CharField(blank=True, max_length=20, verbose_name='\u82f1\u8bed')),
                ('zhengzhi', models.CharField(blank=True, max_length=20, verbose_name='\u653f\u6cbb')),
                ('lishi', models.CharField(blank=True, max_length=20, verbose_name='\u5386\u53f2')),
                ('dili', models.CharField(blank=True, max_length=20, verbose_name='\u5730\u7406')),
                ('shengwu', models.CharField(blank=True, max_length=20, verbose_name='\u751f\u7269')),
                ('zongfen', models.CharField(blank=True, max_length=20, verbose_name='\u603b\u5206')),
                ('xiaozongfen', models.CharField(blank=True, max_length=20, verbose_name='\u5c0f\u603b\u5206')),
                ('nianji_mingci', models.CharField(blank=True, max_length=10, verbose_name='\u5e74\u7eaa\u540d\u6b21')),
                ('banji_mingci', models.CharField(blank=True, max_length=10, verbose_name='\u73ed\u7ea7\u540d\u6b21')),
                ('Notes', models.TextField(blank=True, verbose_name='\u5907\u6ce8')),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u6210\u7ee9',
                'verbose_name_plural': '\u6210\u7ee9',
            },
        ),
        migrations.CreateModel(
            name='jiazhang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u59d3\u540d')),
                ('xingbie', models.CharField(choices=[('boy', '\u7537'), ('girl', '\u5973')], max_length=20, verbose_name='\u59d3\u522b')),
                ('alias', models.CharField(blank=True, max_length=20, verbose_name='\u522b\u540d')),
                ('tel', models.CharField(blank=True, max_length=30, verbose_name='\u7535\u8bdd')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='\u90ae\u7bb1')),
                ('weixin_id', models.CharField(blank=True, max_length=100, verbose_name='\u5fae\u4fe1\u4f01\u4e1a\u53f7\u7528\u6237ID')),
                ('Notes', models.TextField(blank=True, verbose_name='\u5907\u6ce8')),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u5bb6\u957f',
                'verbose_name_plural': '\u5bb6\u957f',
            },
        ),
        migrations.CreateModel(
            name='kaohao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(unique=True, verbose_name='\u8003\u53f7')),
                ('biaoji', models.BooleanField(default=False, help_text='\u6807\u8bb0\u662f\u5426\u4f7f\u7528\uff0c\u9ed8\u8ba4\u672a\u4f7f\u7528', verbose_name='\u6807\u8bb0\u72b6\u6001')),
                ('Notes', models.TextField(blank=True, verbose_name='\u5907\u6ce8')),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u8003\u53f7',
                'verbose_name_plural': '\u8003\u53f7',
            },
        ),
        migrations.CreateModel(
            name='piliang_daoru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=90, verbose_name='\u5bfc\u5165\u540d\u79f0')),
                ('excl_file', models.FileField(help_text='\u4e0a\u4f20\u7684excl\u5fc5\u987b\u7b26\u5408\u6a21\u677f\u89c4\u5219', upload_to='./update/%Y%m%d', verbose_name='excl\u8868\u683c')),
                ('daoru_biaoshi', models.CharField(blank=True, default='0', help_text='1\u4e3a\u8868\u793a\u5df2\u5bfc\u5165\uff0c\u9ed8\u8ba40\u8868\u793a\u672a\u5bfc\u5165', max_length=1, verbose_name='\u5bfc\u5165\u6807\u8bc6')),
                ('note', models.TextField(blank=True, verbose_name='\u5907\u6ce8')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='\u65e5\u671f')),
            ],
            options={
                'verbose_name': '\u6210\u7ee9\u6279\u91cf\u5bfc\u5165',
                'verbose_name_plural': '\u6210\u7ee9\u6279\u91cf\u5bfc\u5165',
            },
        ),
        migrations.CreateModel(
            name='type_chengji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u6240\u6709\u73ed\u7ea7\u5171\u4eab\u4e00\u5957\u6210\u7ee9\u7c7b\u578b', max_length=200, unique=True, verbose_name='\u6210\u7ee9\u7c7b\u578b')),
                ('biaoji', models.BooleanField(default=False, help_text='\u9ed8\u8ba4\u53ef\u89c1,\u9884\u7559\u63a5\u53e3\uff0c\u4e0d\u5fc5\u7406\u4f1a', verbose_name='\u662f\u5426\u5173\u95ed')),
                ('Notes', models.TextField(blank=True, verbose_name='\u5907\u6ce8')),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u6210\u7ee9\u7c7b\u578b',
                'verbose_name_plural': '\u6210\u7ee9\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='xuesheng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xuehao', models.IntegerField(verbose_name='\u5b66\u53f7')),
                ('name', models.CharField(max_length=20, verbose_name='\u59d3\u540d')),
                ('xingbie', models.CharField(choices=[('boy', '\u7537'), ('girl', '\u5973')], max_length=20, verbose_name='\u6027\u522b')),
                ('alias', models.CharField(blank=True, max_length=20, verbose_name='\u522b\u540d')),
                ('tel', models.CharField(blank=True, max_length=20, verbose_name='\u7535\u8bdd')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='\u90ae\u7bb1')),
                ('weixin_id', models.CharField(blank=True, help_text='\u53ef\u4ee5\u4e0d\u586b\uff0c\u9884\u7559\u63a5\u53e3', max_length=100, verbose_name='\u5fae\u4fe1\u7528\u6237ID')),
                ('Notes', models.TextField(blank=True, verbose_name='\u5907\u6ce8')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('banji_id', models.ForeignKey(help_text='\u5b66\u751f\u5c5e\u4e8e\u90a3\u4e2a\u73ed\u7ea7', on_delete=django.db.models.deletion.CASCADE, to='baishi.banji', verbose_name='\u73ed\u7ea7')),
                ('jiazhang_id', models.ManyToManyField(to='baishi.jiazhang', verbose_name='\u5b66\u751f\u7ed1\u5b9a\u5bb6\u957f')),
                ('kaohao_id', models.OneToOneField(help_text='\u5b66\u751f\u7684\u8003\u53f7\u552f\u4e00', on_delete=django.db.models.deletion.CASCADE, to='baishi.kaohao', verbose_name='\u8003\u53f7')),
            ],
            options={
                'verbose_name': '\u5b66\u751f\u7ed1\u5b9a\u73ed\u7ea7\u548c\u5bb6\u957f',
                'verbose_name_plural': '\u5b66\u751f\u7ed1\u5b9a\u73ed\u7ea7\u548c\u5bb6\u957f',
            },
        ),
        migrations.AddField(
            model_name='piliang_daoru',
            name='chengji_leixing',
            field=models.ForeignKey(help_text='\u5982\u679c\u9009\u9519\u6210\u7ee9\u7c7b\u578b\u5bfc\u5165\uff0c\u4f1a\u591a\u51fa\u91cd\u590d\u7684\u6210\u7ee9\u54e6', on_delete=django.db.models.deletion.CASCADE, to='baishi.type_chengji', verbose_name='\u6210\u7ee9\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='chengjibiao',
            name='type_chengji_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baishi.type_chengji', verbose_name='\u6210\u7ee9\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='chengjibiao',
            name='xuesheng_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baishi.xuesheng', verbose_name='\u5b66\u751f'),
        ),
    ]
