# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-25 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baishi', '0002_auto_20170325_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='piliang_xuesheng_jiazhang_daoru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=90, verbose_name='\u5bfc\u5165\u540d\u79f0')),
                ('excl_file', models.FileField(help_text='\u4e0a\u4f20\u7684excl\u5fc5\u987b\u7b26\u5408\u6a21\u677f\u89c4\u5219', upload_to='./update/%Y%m%d', verbose_name='excl\u8868\u683c')),
                ('daoru_biaoshi', models.CharField(blank=True, default='0', help_text='1\u4e3a\u8868\u793a\u5df2\u5bfc\u5165\uff0c\u9ed8\u8ba40\u8868\u793a\u672a\u5bfc\u5165', max_length=1, verbose_name='\u5bfc\u5165\u6807\u8bc6')),
                ('note', models.TextField(blank=True, verbose_name='\u5907\u6ce8')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='\u65e5\u671f')),
                ('banji_leixing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baishi.type_chengji', verbose_name='\u73ed\u7ea7\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u5b66\u751f\u5bb6\u957f\u6279\u91cf\u5bfc\u5165',
                'verbose_name_plural': '\u5b66\u751f\u5bb6\u957f\u6279\u91cf\u5bfc\u5165',
            },
        ),
        migrations.AlterField(
            model_name='jiazhang',
            name='tel',
            field=models.CharField(max_length=30, unique=True, verbose_name='\u7535\u8bdd'),
        ),
    ]
