# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-15 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(help_text='\u4e3b\u673a\u540d', max_length=100, verbose_name='\u4e3b\u673a\u540d')),
                ('hostip', models.GenericIPAddressField(help_text='\u4e3b\u673aip,\u5fc5\u987b\u552f\u4e00', unique=True, verbose_name='\u4e3b\u673aIP')),
                ('hostport', models.IntegerField(default=22, verbose_name='SSH\u7aef\u53e3')),
                ('hostuser', models.CharField(help_text='\u4e3b\u673a\u7528\u6237', max_length=50, verbose_name='\u4e3b\u673a\u7528\u6237')),
                ('hostspassword', models.CharField(help_text='\u4e3b\u673a\u5bc6\u7801', max_length=32, verbose_name='\u4e3b\u673a\u5bc6\u7801')),
                ('node', models.TextField(help_text='\u5907\u6ce8', verbose_name='\u5907\u6ce8')),
                ('createdate', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u4e3b\u673a\u4fe1\u606f',
                'verbose_name_plural': '\u4e3b\u673a\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jifang', models.CharField(help_text='\u673a\u623f\u73af\u5883,\u6df1\u5733\u6c99\u6cb3\u673a\u623f,\u5e7f\u5dde\u8087\u5e86\u673a\u623f,\u6210\u90fd\u673a\u623f', max_length=100, unique=True, verbose_name='IDC\u673a\u623f')),
                ('createdate', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IDC',
                'verbose_name_plural': 'IDC',
            },
        ),
        migrations.AddField(
            model_name='hosts',
            name='idc_id',
            field=models.ForeignKey(help_text='\u4e3b\u673a\u5f52\u5c5e\u90a3\u4e2a\u673a\u623f', on_delete=django.db.models.deletion.CASCADE, to='idc.idc', verbose_name='IDC\u673a\u623f'),
        ),
    ]
