# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-15 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='hostport',
            field=models.IntegerField(blank=True, default=22, verbose_name='SSH\u7aef\u53e3'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='node',
            field=models.TextField(blank=True, help_text='\u5907\u6ce8', verbose_name='\u5907\u6ce8'),
        ),
    ]
