# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-04 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc', '0002_auto_20161215_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosts',
            name='xitong',
            field=models.CharField(choices=[('linux', 'linux'), ('windows', 'windows')], default='linux', help_text='\u7cfb\u7edf', max_length=100, verbose_name='\u7cfb\u7edf'),
        ),
    ]
