# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-25 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc', '0003_hosts_xitong'),
    ]

    operations = [
        migrations.CreateModel(
            name='chengduneiwang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=100, null=True, verbose_name='ip')),
                ('guanli', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7ba1\u7406\u5458')),
                ('mima', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5bc6\u7801')),
                ('beizhu_yonghu', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5907\u6ce8-\u7528\u9014')),
                ('chushi_shiyong_riqi', models.CharField(blank=True, max_length=50, null=True)),
                ('zhuyao_shiyongzhe', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u4e3b\u8981\u4f7f\u7528\u8005')),
                ('shebeileixing', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8bbe\u5907\u7c7b\u578b')),
                ('guanli_dizhi', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7ba1\u7406\u5730\u5740')),
                ('wifi_ssid', models.CharField(blank=True, max_length=100, null=True, verbose_name='wiif_ssid')),
                ('wifi_pwd', models.CharField(blank=True, max_length=128, null=True, verbose_name='wiif_pwd')),
            ],
            options={
                'ordering': ['pk'],
                'verbose_name': '\u6210\u90fd\u5185\u7f51',
                'verbose_name_plural': '\u6210\u90fd\u5185\u7f51',
            },
        ),
        migrations.CreateModel(
            name='shahexianshangyingyong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabanlujing', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u53d1\u7248\u8def\u5f84')),
                ('fuwuming', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u670d\u52a1\u540d')),
                ('rizhilujing', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u65e5\u5fd7\u8def\u5f84')),
                ('qidongjiaoben', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u542f\u52a8\u811a\u672c')),
                ('fuwuqi', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u670d\u52a1\u5668')),
                ('duankou', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7aef\u53e3')),
                ('beizhu', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'ordering': ['pk'],
                'verbose_name': '\u7ebf\u4e0a\u4e1a\u52a1\u5206\u5e03',
                'verbose_name_plural': '\u7ebf\u4e0a\u4e1a\u52a1\u5206\u5e03',
            },
        ),
        migrations.AlterModelOptions(
            name='hosts',
            options={'verbose_name': '\u7ebf\u4e0a\u4e3b\u673a\u4fe1\u606f', 'verbose_name_plural': '\u7ebf\u4e0a\u4e3b\u673a\u4fe1\u606f'},
        ),
        migrations.AlterField(
            model_name='hosts',
            name='hostip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='\u4e3b\u673aIP'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='hostname',
            field=models.CharField(blank=True, help_text='\u4e3b\u673a\u540d', max_length=100, verbose_name='\u4e3b\u673a\u540d'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='hostport',
            field=models.IntegerField(blank=True, default=22, null=True, verbose_name='\u7aef\u53e3'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='hostspassword',
            field=models.CharField(blank=True, help_text='\u4e3b\u673a\u5bc6\u7801', max_length=32, verbose_name='\u4e3b\u673a\u5bc6\u7801'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='hostuser',
            field=models.CharField(blank=True, help_text='\u4e3b\u673a\u7528\u6237', max_length=50, verbose_name='\u4e3b\u673a\u7528\u6237'),
        ),
    ]
