# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-03 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apptype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u5e94\u7528')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='\u5907\u6ce8')),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u5e94\u7528\u7c7b\u578b',
                'verbose_name_plural': '\u5e94\u7528\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='containerip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='docker\u4e3b\u673aip')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='\u5907\u6ce8')),
                ('active', models.BooleanField(default=False, help_text='\u9ed8\u8ba4IP\u672a\u4f7f\u7528', verbose_name='\u6fc0\u6d3b')),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u5bb9\u5668IP',
                'verbose_name_plural': '\u5bb9\u5668IP',
            },
        ),
        migrations.CreateModel(
            name='dockerhost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='docker\u4e3b\u673a')),
                ('ip', models.GenericIPAddressField(verbose_name='docker\u5bbf\u4e3b\u673aip')),
                ('mask', models.CharField(blank=True, default=22, max_length=255, null=True, verbose_name='\u63a9\u7801')),
                ('gateway', models.GenericIPAddressField(verbose_name='\u7f51\u5173')),
                ('docker_username', models.CharField(blank=True, max_length=255, verbose_name='docker_\u7528\u6237\u540d')),
                ('docker_password', models.CharField(blank=True, max_length=255, verbose_name='docker_\u5bc6\u7801')),
                ('pname', models.CharField(blank=True, max_length=255, verbose_name='docker\u4e0a\u5c42\u7269\u7406\u673a')),
                ('pip', models.GenericIPAddressField(verbose_name='docker\u4e0a\u5c42\u7269\u7406\u673aip')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='docker\u4e0a\u5c42\u7528\u6237\u540d')),
                ('password', models.CharField(blank=True, max_length=255, verbose_name='docker\u4e0a\u5c42\u5bc6\u7801')),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'docker\u4e3b\u673a',
                'verbose_name_plural': 'docker\u4e3b\u673a',
            },
        ),
        migrations.CreateModel(
            name='dockerimages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255, verbose_name='docker\u955c\u50cf\u522b\u540d')),
                ('name', models.CharField(max_length=255, verbose_name='docker\u955c\u50cf')),
            ],
            options={
                'verbose_name': 'docker\u955c\u50cf',
                'verbose_name_plural': 'docker\u955c\u50cf',
            },
        ),
        migrations.CreateModel(
            name='idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u673a\u623f')),
            ],
            options={
                'verbose_name': '\u673a\u623f',
                'verbose_name_plural': '\u673a\u623f',
            },
        ),
        migrations.CreateModel(
            name='managecontainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, help_text='\u7a0b\u5e8f\u81ea\u52a8\u751f\u6210\uff0c\u4e0d\u9700\u8981\u586b\u5199.\u683c\u5f0f:\u540d\u79f0_\u5bb9\u5668IP_\u5f00\u653e\u7aef\u53e3', max_length=255, null=True, verbose_name='\u5bb9\u5668\u7684\u522b\u540d')),
                ('openport', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5f00\u653e\u7684\u7aef\u53e3')),
                ('state1', models.CharField(choices=[('1', '\u672a\u786e\u5b9a\u914d\u7f6e'), ('2', '\u914d\u7f6e\u786e\u5b9a'), ('3', '\u5bb9\u5668\u5df2\u521b\u5efa'), ('4', '\u5bb9\u5668\u521b\u5efa\u5931\u8d25')], default='1', max_length=1, verbose_name='\u5bb9\u5668\u521b\u5efa\u72b6\u6001')),
                ('extensions_directory', models.CharField(blank=True, help_text='\u547d\u540d\u683c\u5f0f\u4e3adir_id_ip', max_length=255, verbose_name='\u5916\u90e8\u6302\u8f7d\u76ee\u5f55')),
                ('container_id', models.CharField(blank=True, max_length=255, verbose_name='\u5bb9\u5668ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('apptype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dockermanageplatform.apptype', verbose_name='\u5e94\u7528\u7c7b\u578b')),
                ('containerip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dockermanageplatform.containerip', verbose_name='\u5bb9\u5668IP')),
                ('dockerhost_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dockermanageplatform.dockerhost', verbose_name='docker\u4e3b\u673a')),
                ('dockerimages_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dockermanageplatform.dockerimages', verbose_name='docker\u955c\u50cf')),
            ],
            options={
                'verbose_name': '\u7ba1\u7406\u5bb9\u5668',
                'verbose_name_plural': '\u7ba1\u7406\u5bb9\u5668',
            },
        ),
        migrations.CreateModel(
            name='registerscript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='\u811a\u672c')),
                ('shell', models.TextField(blank=True, verbose_name='shell')),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u6ce8\u518c\u811a\u672c',
                'verbose_name_plural': '\u6ce8\u518c\u811a\u672c',
            },
        ),
        migrations.AddField(
            model_name='managecontainer',
            name='registerscript_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dockermanageplatform.registerscript', verbose_name='\u6ce8\u518c\u811a\u672c'),
        ),
        migrations.AddField(
            model_name='dockerhost',
            name='idc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dockermanageplatform.idc'),
        ),
    ]
